--- 
javascripts: 
- proto:
  - prototype
  - effects
  - controls
- rest: 
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - application
  - facebox
stylesheets: 
- base:
  - post
  - jquery-ui-1.7.2.custom
  - facebox
  
